server:
  port: 8088

spring:
  cloud:
    gateway:
      routes:
        - id: FLEETNAV-SERVICE
          uri: lb://FLEETNAV-SERVICE
          predicates:
            - Path=/api/v1/{tenantId}/**

        - id: CHAT-SERVICE
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/api/v1/chat/**

        - id: MULTITENANCY-SERVICE
          uri: lb://MULTITENANCY-SERVICE
          predicates:
            - Path=/api/v1/**

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka