server:
  port: 8088
spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/*]":
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: MULTITENANCY-SERVICE
          uri: lb://MULTITENANCY-SERVICE
          predicates:
            - Path=/api/v1/**
        - id: CHAT-SERVICE
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/socket/v1/**
        - id: CHAT-SERVICE
          uri: lb:ws://CHAT-SERVICE
          predicates:
            - Path=/socket/v1/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://fleetnav-eureka-server-0-0-1.onrender.com/eureka
