server:
  port: 8083
  servlet:
    context-path: /socket/v1

spring:
  data:
    mongodb:
      uri: mongodb+srv://ralexale:tK13NUBsfBVd0gQ1@fleetnavdb.wvnbvf0.mongodb.net/
      database: fleetNavChat

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
