server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://root:example@localhost:5333/
      database: fleetNavChat

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka