server:
  port: 8083
  servlet:
    context-path: /socket/v1

spring:
  data:
    mongodb:
      uri: mongodb://fleet-dev:fleet-dev01@ac-fo4eobj-shard-00-00.gaxwgxe.mongodb.net:27017,ac-fo4eobj-shard-00-01.gaxwgxe.mongodb.net:27017,ac-fo4eobj-shard-00-02.gaxwgxe.mongodb.net:27017/?replicaSet=atlas-w1x0kw-shard-0&ssl=true&authSource=admin
      database: fleetNavChat

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://fleetnav-eureka-server-0-0-1.onrender.com/eureka
