server:
  port: 8083
  servlet:
    context-path: /api/v1

spring:
  data:
    mongodb:
      uri: uri: mongodb+srv://ralexale:tK13NUBsfBVd0gQ1@fleetnavdb.wvnbvf0.mongodb.net/
      database: fleetNavChat

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
    enpoints:
      web:
        exposure:
          include: health

    enpoint:
      health:
        show-details: always

resilience4j:
  circuitbreaker:
    instances:
      ratingHotelBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

    retry:
      instances:
        ratingHotelService:
          max-attemps: 3
          wait-duration: 5s
