server:
  port: 8081
  servlet:
    context-path: /api/v1

hibernate:
  connection:
    username: postgres
    password: postgres
    driver_class: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/fleetNav
  ddl-auto: 
  show_sql: true
  dialect: org.hibernate.dialect.PostgreSQLDialect

spring:
  datasource:
    url: ${hibernate.connection.url}
    username: ${hibernate.connection.username}
    password: ${hibernate.connection.password}
    driverClassName: ${hibernate.connection.driver_class}
  jpa:
    show-sql: ${hibernate.show_sql}
    generate-ddl: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: ${hibernate.dialect}
        ddl-auto: ${hibernate.ddl-auto}
        show_sql: ${hibernate.show_sql}
        multiTenancy: SCHEMA
        tenant_identifier_resolver: com.fleetNavmultitenantservice.config.config.multitenant.hibernate.TenantIdentifierResolver
        multi_tenant_connection_provider: com.fleetNavmultitenantservice.config.multitenant.hibernate.SchemaMultiTenantConnectionProvider

flyway:
  url: ${hibernate.connection.url}
  user: ${hibernate.connection.username}
  password: ${hibernate.connection.password}
  baselineOnMigrate: true
  enabled: false


eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka